# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           :year/:month/:title.html
relative_permalinks: true

# Setup
title:               Hemingway
tagline:             'A cyber hideout for fun and research.'
description:         'This cite contains posts and my personal projects, research interests, crazy ideas, and casual thought dumps.'
url:                 http://mwzhang.com
baseurl:             '/en'
paginate:            5

# About/contact
author:
  name:              Mingwei Zhang
  url:               https://twitter.com/digizeph
  email:             digizeph@gmail.com

# Custom vars
version:             1.0.0
